version: '2'
services:
  jhipstercrudtestapplication-postgresql:
    image: postgres:12.1
    # volumes:
    #     - ~/volumes/jhipster/jhipsterCrudTestApplication/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=jhipsterCrudTestApplication
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
